### ISSUE TITLE
Vehicles, Array out of bound. 

### ISSUE THREAD

**Issue by Sasuke-Uchiha** [Open-GTO/foreach#8]
`foreach(new i : Vehicle) DestroyVehicle(i);`

Using this code on my FilterScriptExit crashdetect shows following errors;

> [11:15:34] [debug] Run time error 4: "Array index out of bounds"
> [11:15:34] [debug]  Attempted to read/write array element at index 2001 in array of size 2001
> [11:15:34] [debug] AMX backtrace:
> [11:15:34] [debug] #0 0000559c in public OnFilterScriptExit () at ..\Types\Race01.inc:157

**Comment by ziggi** [comment]
https://github.com/Open-GTO/foreach#remove-all-existed-vehicles-and-actors
